name: Lint code

on:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/linters.yaml"
      - "pyproject.toml"
      - "poetry.lock"
  push:
    paths:
      - "src/**"
      - ".github/workflows/linters.yaml"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8

      - name: Run black
        run: poetry run black --check src

      - name: Run isort
        run: poetry run isort --check-only src

      - name: Run mypy
        run: poetry run mypy src
